name: MLB-Tunnel-Bot

on:
  schedule:
    # Runs every day at 3:50 PM UTC (11:50 am EST)
    - cron: "55 16 * * *" # right now debugging at 4:55 UTC

jobs:
  MLB-Tunnel-Bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py

      - name: Update README with latest image
        run: |
          image_path="MLB-Tunnel-Bot/assets/tunnel_plot.png"
          sed -i 's|PLACEHOLDER_FOR_LATEST_IMAGE|'"$image_path"'|' README.md

      - name: Commit changes To README.md and latest tunnel images
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update README with latest image"
          git push
