name: MLB-Tunnel-Bot

on:
  schedule:
    # Runs every day at 3:50 PM UTC (11:50 am EST)
    - cron: "50 15 * * *"
  workflow_dispatch:

jobs:
  MLB-Tunnel-Bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

      - name: Update README with latest image
        run: |
          image_path="MLB-Tunnel-Bot/assets/tunnel_plot.png"
          sed -i 's|PLACEHOLDER_FOR_LATEST_IMAGE|'"$image_path"'|' README.md

      - name: Commit changes To README.md and latest tunnel images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update README with latest image"
          git push
